Repository leehyeji319/WhereisMyHome08, pull requests merged in 2022-11, with the labels that each got.

#1 feat: 실거래가 조회기능 추가
  backend/pom.xml
  backend/src/main/java/com/ssafy/myhome/controller/HouseInfoController.java
  backend/src/main/java/com/ssafy/myhome/model/dao/HouseInfoDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/HouseInfoDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dto/HouseInfo.java
  backend/src/main/java/com/ssafy/myhome/model/dto/MyPageUserInfo.java
  backend/src/main/java/com/ssafy/myhome/model/service/HouseInfoService.java
  backend/src/main/java/com/ssafy/myhome/model/service/HouseInfoServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/mapper/resultMaps.xml
Labels: 기능 추가

#2 feat: 관심 아파트 기능 추가
  backend/pom.xml
  backend/src/main/java/com/ssafy/myhome/controller/HouseInfoController.java
  backend/src/main/java/com/ssafy/myhome/controller/InterestHouseController.java
  backend/src/main/java/com/ssafy/myhome/model/dao/HouseInfoDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestHouseDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestHouseDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dto/InterestBoard.java
  backend/src/main/java/com/ssafy/myhome/model/dto/InterestHouse.java
  backend/src/main/java/com/ssafy/myhome/model/dto/MyPageUserInfo.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestHouseService.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestHouseServiceImpl.java
  backend/src/main/resources/mapper/resultMaps.xml
Labels: 기능 추가

#3 fix: house service 메서드 명 수정
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestHouseDao.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestHouseServiceImpl.java
Labels: 오류 수정

#4 feat: User Interest Board 기능추가
  backend/src/main/java/com/ssafy/myhome/controller/InterestBoardController.java
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestBoardDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestBoardDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestHouseDao.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestBoardService.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestBoardServiceImpl.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestHouseServiceImpl.java
  backend/src/main/resources/mapper/resultMaps.xml
Labels: 🕹 기능, 🔥 백엔드

#5 feat: Interest Area CRUD 완성
  backend/resources/Dump20221117.sql
  backend/src/main/java/com/ssafy/myhome/controller/InterestAreaController.java
  backend/src/main/java/com/ssafy/myhome/controller/NoticeController.java
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestAreaDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestAreaDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dao/NoticeDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/NoticeDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dto/CommercialArea.java
  backend/src/main/java/com/ssafy/myhome/model/dto/CommercialLabel.java
  backend/src/main/java/com/ssafy/myhome/model/dto/CommercialTypeValue.java
  backend/src/main/java/com/ssafy/myhome/model/dto/DongCode.java
  backend/src/main/java/com/ssafy/myhome/model/dto/InterestArea.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestAreaService.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestAreaServiceImpl.java
  backend/src/main/java/com/ssafy/myhome/model/service/NoticeService.java
  backend/src/main/java/com/ssafy/myhome/model/service/NoticeServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/mapper/resultMaps.xml
Labels: 🕹 기능, 🔥 백엔드

#6 feat: user 기능 추가
  backend/src/main/java/com/ssafy/myhome/config/TransactionConfig.java
  backend/src/main/java/com/ssafy/myhome/controller/AuthController.java
  backend/src/main/java/com/ssafy/myhome/exception/advice/IllegalUserException.java
  backend/src/main/java/com/ssafy/myhome/exception/advice/UnAuthorizedException.java
  backend/src/main/java/com/ssafy/myhome/model/dao/AuthDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/AuthDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestHouseDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dto/CompanyInfo.java
  backend/src/main/java/com/ssafy/myhome/model/dto/UserInfo.java
  backend/src/main/java/com/ssafy/myhome/model/service/AuthService.java
  backend/src/main/java/com/ssafy/myhome/model/service/AuthServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/mapper/resultMaps.xml
Labels: 🕹 기능, 🔥 백엔드

#7 feat: user mypage 기능 추가
  backend/src/main/java/com/ssafy/myhome/controller/AuthController.java
  backend/src/main/java/com/ssafy/myhome/controller/UserController.java
  backend/src/main/java/com/ssafy/myhome/model/dao/AuthDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/AuthDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestBoardDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dao/NoticeDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dao/UserDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/UserDao.xml
  backend/src/main/java/com/ssafy/myhome/model/dto/MyPageUserInfo.java
  backend/src/main/java/com/ssafy/myhome/model/dto/UserInfo.java
  backend/src/main/java/com/ssafy/myhome/model/service/AuthService.java
  backend/src/main/java/com/ssafy/myhome/model/service/AuthServiceImpl.java
  backend/src/main/java/com/ssafy/myhome/model/service/UserService.java
  backend/src/main/java/com/ssafy/myhome/model/service/UserServiceImpl.java
  backend/src/main/resources/mapper/resultMaps.xml
Labels: 🕹 기능, 🔥 백엔드, 🛠 리팩토링

#8 feat: 프론트 기본 폴더구조, 라우터 기본 세팅
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/components/layout/TheHeaderNavbar.vue
  frontend/src/components/layout/ThePageHeader.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/AboutView.vue
  frontend/src/views/AppMain.vue
  frontend/src/views/HomeView.vue
Labels: ⚙️ 설정, 🌷 프론트

#14 refactor: 관심 아파트 등록 메서드 수정
  backend/src/main/java/com/ssafy/myhome/controller/InterestHouseController.java
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestHouseDao.java
  backend/src/main/java/com/ssafy/myhome/model/dao/InterestHouseDao.xml
  backend/src/main/java/com/ssafy/myhome/model/service/InterestHouseService.java
  backend/src/main/java/com/ssafy/myhome/model/service/InterestHouseServiceImpl.java
  frontend/src/components/board/BoardList.vue
Labels: 🔥 백엔드, 🛠 리팩토링, 🚐 핫픽스
